# Generated by Django 4.1.4 on 2023-01-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_groupmembers_gm_id_alter_groupposts_gp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('email_code', models.CharField(max_length=6)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
