# Generated by Django 4.1.4 on 2023-01-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriends',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
