# Generated by Django 4.1.4 on 2023-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userfriends_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('image', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
