# Generated by Django 4.1.4 on 2023-01-20 07:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='image',
            field=models.ImageField(default='posts/image.jpg', upload_to=core.models.image_path),
        ),
    ]
